// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9oglvH4CC55IgrQ2EYD1diMGWWO4OWk',
    appId: '1:1053568145006:web:35246040b41684ab49787f',
    messagingSenderId: '1053568145006',
    projectId: 'group20b',
    authDomain: 'group20b.firebaseapp.com',
    storageBucket: 'group20b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCdwuqPLli-pV0iZ4HVYil8MGdT7Upikk',
    appId: '1:1053568145006:android:942a326b1f24d51d49787f',
    messagingSenderId: '1053568145006',
    projectId: 'group20b',
    storageBucket: 'group20b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD122QiCKW6TxbhlMHHH7j-EE_1UaEo6J4',
    appId: '1:1053568145006:ios:7aa9b6d9eabcfd5249787f',
    messagingSenderId: '1053568145006',
    projectId: 'group20b',
    storageBucket: 'group20b.firebasestorage.app',
    iosBundleId: 'com.example.group20b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD122QiCKW6TxbhlMHHH7j-EE_1UaEo6J4',
    appId: '1:1053568145006:ios:7aa9b6d9eabcfd5249787f',
    messagingSenderId: '1053568145006',
    projectId: 'group20b',
    storageBucket: 'group20b.firebasestorage.app',
    iosBundleId: 'com.example.group20b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC9oglvH4CC55IgrQ2EYD1diMGWWO4OWk',
    appId: '1:1053568145006:web:bc7fe8e5591fe22c49787f',
    messagingSenderId: '1053568145006',
    projectId: 'group20b',
    authDomain: 'group20b.firebaseapp.com',
    storageBucket: 'group20b.firebasestorage.app',
  );

}